### ISSUE TITLE
How can I get images300_array data?

### ISSUE THREAD

**Issue by zhangyinglu** [hnjzbss/EKAGen#6]
Before I run the test code, do I need to generate the cam-mask first? Which code should I use to generate the mask?

**Comment by zhangyinglu** [comment]
Additionally, when I run generate_adm.py, should I still use MIMIC_best_weight.pth for IU Xray dataset?

**Comment by hnjzbss** [comment]
> Before I run the test code, do I need to generate the cam-mask first? Which code should I use to generate the mask?

IU X-Ray does not provide category labels, so there is no classification model trained for IU X-Ray. You can use generate_adm.py to load MIMIC_best_weight.pth to generate masks, or you can download the data we generated from https://huggingface.co/ShenshenBu/EKAGen/tree/main.
